# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6be941c25c9e0af3cfe05e223957b24e4a7edcb714653eff89e719f2eac6700971152126438ee966625f7fe589f0e88d5ff6402d83292ea344163f24cc3e7973

test:
  secret_key_base: eb9df7fbbac3de06af49259346d59f4dde12102c026c9e2678dbaf763b812e25a75376d4aedf839a8afffc16d036d61e98346da7e972db5e3b6130ed6b36667d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
